# Generated by Django 3.2.25 on 2024-06-17 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('choose_an_option', 'Choose an option'), ('racism', 'Racism'), ('sexism', 'Sexism'), ('inappropriate', 'Inappropriate'), ('personal_attack', 'Personal attack')], default='Choose an option', max_length=32)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joke.joke')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
